services:
  flask-app:
    build: .
    ports:
      - "5002:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    networks:
      - shared-network
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - shared-network

networks:
  shared-network:
    external: true